plugins {
    id 'com.android.application'
}

android {
    namespace 'com.webview.chatgpt'
    compileSdk 35
    buildToolsVersion "35.0.2"

    defaultConfig {
        applicationId "com.webview.chatgpt"
        minSdk 29
        targetSdk 35
        versionCode 120
        versionName "1.2_initial"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            vcsInfo.include = false
        }
    }

    packaging {
        resources.excludes.add("META-INF/com/android/build/gradle/app-metadata.properties")
        resources.excludes.add("META-INF/*.version")
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}